cecomsap_bi:
  target: dev
  outputs:
    dev:
      type:     postgres
      host:     "{{ env_var('PG_HOST', 'localhost') }}"
      port:     "{{ env_var('PG_PORT', '5432') | int }}"
      dbname:   "{{ env_var('PG_DATABASE', 'dw_cecomsap') }}"
      user:     "{{ env_var('PG_USER', 'dw_user') }}"
      password: "{{ env_var('PG_PASSWORD', 'dw_pass123') }}"
      schema:   staging
      threads:  4
